eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    registry-fetch-interval-seconds: 5

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
        timeout:
          enabled: true
 
spring:
  http:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB
      
 
#oauth2
oauth2:
  client:
    check-token-uri: http://onlinejudge-ifa-oauth/onlinejudge-ifa-oauth/oauth/check_token
    accessTokenUri: http://onlinejudge-ifa-oauth/onlinejudge-ifa-oauth/oauth/token
  resource:
    user-info-uri: http://onlinejudge-ifa-oauth/onlinejudge-ifa-oauth/users/current