#MongoDB
spring:
  data:
    mongodb:
      host: 127.0.0.1
      username: onlinejudge
      password: P@ssword123
      database: onlinejudge
      port: 27017

server:
  context-path: /onlinejudge-ifa-oauth
  port: 0

#Client credentical
onlinejudge:
    ms:
        user:
            id: userService
            password: userService@password
        contest:
            id: contestService
            password: contestService@password
        resource:
            id: resourceService
            password: resourceService@password
        judge:
            id: judgeService
            password: judgeService@password
